### PR TITLE
Fix protocol error when using app parameter

### PR DESCRIPTION
**Pull request by abeverley**
The `firewall` command defaults to `proto tcp`. However, the `app` parameter in UFW does not allow a protocol to be specified, so the command always fails with `error: "Do not specify protocol parameter with app parameter"`.

This patch removes the default.

### CODE REVIEW

**Comment by krimdomu** [comment]
@abeverley 
wouldn't it be better to just remove the proto parameter in the ufw module here? https://github.com/RexOps/rex-recipes/blob/1.3/Rex/Commands/Firewall/Provider/ufw.pm#L145

Because than, the proto option will be set to tcp for every other module.

**Comment by abeverley** [comment]
I don't really mind. It just seems a bit messy adding it and then removing it though. And a user won't get an error if they do this:

```
firewall "some-name",
    provider => 'ufw',
    ensure   => "present",
    action   => "accept",
    proto    => "tcp",
    app      => 'OpenSSH';
```

**Comment by krimdomu** [comment]
you're right, then it might be better to add the tcp default to these providers which can handle them.

**Comment by krimdomu** [comment]
Thanks for the patch. I've just merged it.

**Comment by abeverley** [comment]
Thanks :-)

**Pull request merged**
