### PR TITLE
New way integration Rex and Sparrow

### PR DESCRIPTION
**Pull request by melezhik**
Hi Ferenc! I made a lot of updates to Rex::Misc::Sparrow module to simplify a rex/Sparrow usage/integration. Highlights:
- this version of Rex::Misc::Sparrow is fully compatible with the latest version of Sparrow ( current version of Rex::Misc::Sparrow  won't work with the latest version of Sparrow )
- **configure task** just installs Sparrow and dependencies 
- I decided not to manage  sparrow checkpoints via rex ( for the complexity reasons )
- Instead of  managing checkpoints Rex::Misc::Sparrow just installs a list of plugins with **setup task**
- A new **plugin_run task** runs an installed sparrow plugins in two favours:
  - a whole list 
  - a single plugin ( using --plugin=$name ) parameter

Optionally for  both  favours  one may set a runtime plugin parameters like:

`rex -qw Misc:Sparrow:plugin_run --plugin=df-check --threshold=88`
- sparrow.yml is very simple now and is just a list of sparrow plugins to install:

```
sparrow:
  plugins:
    - df-check
    - nginx-check
    - perlbrew
```
- details at  pod for Rex/Misc/Sparrow/**module**.pm  
- ~~**check** and **dump_config**~~ tasks are gone ( no need for them )

### CODE REVIEW

**Comment by melezhik** [comment]
Add @ferki to watchers

**Comment by ferki** [comment]
Great! I'll review and comment/merge.

**Comment by ferki** [comment]
Nice, it does look simpler, and works well in my quick tests! I'll fix two small typos after merge.

Later on, I might add back the possibility to store settings (like `threshold` for `df-check`) in the YAML/CMDB, so they can be stored in the repo (so `plugin_run` can pick them up from there, and it can be under version control of a project).

**Comment by ferki** [comment]
ps.: I also applied default perltidy

**Comment by melezhik** [comment]
Hi @ferki ! Thank you. I am glad that you found this version much simpler. :smile:  Let me know if anything else you need.

**Pull request merged**
